name: Clang Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - 'llvm/**'
      - '.github/workflows/clang-tests.yml'
  pull_request:
    paths:
      - 'clang/**'
      - 'llvm/**'
      - '.github/workflows/clang-tests.yml'

jobs:
  check_clang:
    name: Test clang,lldb,libclc
    uses: llvm/llvm-project/.github/workflows/llvm-project-tests.yml@release/14.x
    with:
      build_target: check-clang
      projects: clang;lldb;libclc
