name: libclc Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - 'llvm/**'
      - 'libclc/**'
      - '.github/workflows/libclc-tests.yml'
  pull_request:
    paths:
      - 'clang/**'
      - 'llvm/**'
      - 'libclc/**'
      - '.github/workflows/libclc-tests.yml'

jobs:
  check_libclc:
    name: Test libclc
    uses: llvm/llvm-project/.github/workflows/llvm-project-tests.yml@release/14.x
    with:
      build_target: ''
      projects: clang;libclc
