name: LLD Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'lld/**'
      - 'llvm/**'
      - '.github/workflows/lld-tests.yml'
  pull_request:
    paths:
      - 'lld/**'
      - 'llvm/**'
      - '.github/workflows/lld-tests.yml'

jobs:
  check_lld:
    name: Test lld
    uses: llvm/llvm-project/.github/workflows/llvm-project-tests.yml@release/14.x
    with:
      build_target: check-lld
      projects: lld
