name: lldb Tests

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'release/**'
  #   paths:
  #     - 'clang/**'
  #     - 'llvm/**'
  #     - 'lldb/**'
  #     - '.github/workflows/lldb-tests.yml'
  # pull_request:
  #   paths:
  #     - 'clang/**'
  #     - 'llvm/**'
  #     - 'lldb/**'
  #     - '.github/workflows/lldb-tests.yml'

jobs:
  build_lldb:
    name: Build lldb
    uses: llvm/llvm-project/.github/workflows/llvm-project-tests.yml@release/14.x
    with:
      build_target: ''
      projects: clang;lldb
